# Generated by Django 4.0.4 on 2022-04-22 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('population', models.PositiveIntegerField()),
                ('land_area', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('population', models.PositiveBigIntegerField()),
                ('land_area', models.PositiveIntegerField(null=True)),
                ('countries', models.ManyToManyField(related_name='continents', to='geography.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('population', models.PositiveIntegerField()),
                ('is_country_capital', models.BooleanField(default=False)),
                ('special_note', models.CharField(default='', max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_city', to='geography.country')),
            ],
        ),
    ]
